type lesson ={
    lessonTitle: string,
    lessonNumber: string,
    lessonDescription: string,
    lessonVideoSrc: string,
}

export const Lessons: lesson[] = [
    {
        lessonTitle: 'Understanding React Native',
        lessonNumber: "1",
        lessonDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi malesuada rutrum nisi pellentesque placerat. Phasellus gravida quam vitae ante pellentesque, id accumsan nulla blandit. Morbi malesuada aliquam massa vestibulum aliquet. Maecenas at ante sit amet eros fermentum elementum in id arcu. Vivamus laoreet ipsum lorem, nec rutrum erat pretium in. Quisque lacinia, lectus vel convallis ultricies, magna turpis tincidunt tortor, id pulvinar enim neque posuere ante. Aliquam cursus magna quis bibendum malesuada. Vestibulum euismod lacus sed elit euismod blandit. Pellentesque ac ultricies odio. Duis maximus elit id arcu aliquam, sit amet pulvinar mauris sodales. Donec sed felis in lacus faucibus ultrices. Nulla ut accumsan dui. Cras vel viverra purus. Praesent quis malesuada neque. Vivamus et mi ac augue egestas maximus facilisis ac massa.Etiam at diam nec dui volutpat efficitur. Cras faucibus urna non euismod vehicula. Suspendisse vel laoreet ligula. Duis eget nisi eget augue laoreet ultricies quis efficitur enim. Aliquam erat volutpat. Maecenas a risus turpis. Etiam non blandit velit, sed luctus tortor. Praesent at felis quam. Pellentesque nec libero tincidunt, maximus massa ut, imperdiet elit. Phasellus sit amet convallis risus. Sed nec sem erat. Suspendisse dapibus nunc sapien, sit amet placerat sem feugiat a. Phasellus lectus ante, lobortis eget magna a, luctus sodales elit. Aenean et iaculis magna. Vestibulum vel laoreet metus, sed dictum justo. Morbi ac interdum mi, ut ornare tortor. Curabitur faucibus, purus vitae mollis fringilla, turpis ligula venenatis elit, non maximus est nulla luctus mauris. In vel fringilla ex. Suspendisse potenti. Aliquam non porttitor dui. Pellentesque eu libero quis arcu fermentum vehicula ut id metus. Pellentesque elementum accumsan nisi eget pellentesque. Nulla dignissim condimentum elit, in vehicula purus efficitur in. Vivamus sit amet auctor metus. Pellentesque nec pretium diam. Phasellus viverra eu turpis a tincidunt. Cras vel justo nec felis efficitur placerat. Mauris at ipsum vel lorem ultrices sodales quis nec nisi. Quisque at venenatis sapien. Nulla facilisi.Vestibulum vestibulum libero sit amet dui dignissim ullamcorper. Donec venenatis luctus lorem vel congue. Nulla at purus maximus, pharetra nibh eu, vestibulum enim. Duis ultrices justo ut diam viverra, vel scelerisque augue convallis. Quisque id risus sed metus posuere semper a in leo. Nam eu quam purus. Nam eu tellus cursus, suscipit tellus id, condimentum turpis. Aenean vitae lectus mattis, vestibulum ligula id, maximus metus. Integer commodo sapien et feugiat tincidunt. Vivamus tellus purus, placerat sed eros vel, sagittis tempor orci. Nunc suscipit nec sem sit amet dapibus. Nunc nulla metus, vulputate vel tellus sit amet, interdum efficitur orci. Pellentesque vulputate sodales massa non tempus. Suspendisse potenti. Sed eleifend justo et orci auctor, in tempor leo viverra.",
        lessonVideoSrc: "dsafasdfasdf"
    },
    {
        lessonTitle: 'Understanding React Native2',
        lessonNumber: "2",
        lessonDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi malesuada rutrum nisi pellentesque placerat. Phasellus gravida quam vitae ante pellentesque, id accumsan nulla blandit. Morbi malesuada aliquam massa vestibulum aliquet. Maecenas at ante sit amet eros fermentum elementum in id arcu. Vivamus laoreet ipsum lorem, nec rutrum erat pretium in. Quisque lacinia, lectus vel convallis ultricies, magna turpis tincidunt tortor, id pulvinar enim neque posuere ante. Aliquam cursus magna quis bibendum malesuada. Vestibulum euismod lacus sed elit euismod blandit. Pellentesque ac ultricies odio. Duis maximus elit id arcu aliquam, sit amet pulvinar mauris sodales. Donec sed felis in lacus faucibus ultrices. Nulla ut accumsan dui. Cras vel viverra purus. Praesent quis malesuada neque. Vivamus et mi ac augue egestas maximus facilisis ac massa.Etiam at diam nec dui volutpat efficitur. Cras faucibus urna non euismod vehicula. Suspendisse vel laoreet ligula. Duis eget nisi eget augue laoreet ultricies quis efficitur enim. Aliquam erat volutpat. Maecenas a risus turpis. Etiam non blandit velit, sed luctus tortor. Praesent at felis quam. Pellentesque nec libero tincidunt, maximus massa ut, imperdiet elit. Phasellus sit amet convallis risus. Sed nec sem erat. Suspendisse dapibus nunc sapien, sit amet placerat sem feugiat a. Phasellus lectus ante, lobortis eget magna a, luctus sodales elit. Aenean et iaculis magna. Vestibulum vel laoreet metus, sed dictum justo. Morbi ac interdum mi, ut ornare tortor. Curabitur faucibus, purus vitae mollis fringilla, turpis ligula venenatis elit, non maximus est nulla luctus mauris. In vel fringilla ex. Suspendisse potenti. Aliquam non porttitor dui. Pellentesque eu libero quis arcu fermentum vehicula ut id metus. Pellentesque elementum accumsan nisi eget pellentesque. Nulla dignissim condimentum elit, in vehicula purus efficitur in. Vivamus sit amet auctor metus. Pellentesque nec pretium diam. Phasellus viverra eu turpis a tincidunt. Cras vel justo nec felis efficitur placerat. Mauris at ipsum vel lorem ultrices sodales quis nec nisi. Quisque at venenatis sapien. Nulla facilisi.Vestibulum vestibulum libero sit amet dui dignissim ullamcorper. Donec venenatis luctus lorem vel congue. Nulla at purus maximus, pharetra nibh eu, vestibulum enim. Duis ultrices justo ut diam viverra, vel scelerisque augue convallis. Quisque id risus sed metus posuere semper a in leo. Nam eu quam purus. Nam eu tellus cursus, suscipit tellus id, condimentum turpis. Aenean vitae lectus mattis, vestibulum ligula id, maximus metus. Integer commodo sapien et feugiat tincidunt. Vivamus tellus purus, placerat sed eros vel, sagittis tempor orci. Nunc suscipit nec sem sit amet dapibus. Nunc nulla metus, vulputate vel tellus sit amet, interdum efficitur orci. Pellentesque vulputate sodales massa non tempus. Suspendisse potenti. Sed eleifend justo et orci auctor, in tempor leo viverra.",
        lessonVideoSrc: "dsafasdfasdf"
    },
    {
        lessonTitle: 'Understanding React Native',
        lessonNumber: "3",
        lessonDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi malesuada rutrum nisi pellentesque placerat. Phasellus gravida quam vitae ante pellentesque, id accumsan nulla blandit. Morbi malesuada aliquam massa vestibulum aliquet. Maecenas at ante sit amet eros fermentum elementum in id arcu. Vivamus laoreet ipsum lorem, nec rutrum erat pretium in. Quisque lacinia, lectus vel convallis ultricies, magna turpis tincidunt tortor, id pulvinar enim neque posuere ante. Aliquam cursus magna quis bibendum malesuada. Vestibulum euismod lacus sed elit euismod blandit. Pellentesque ac ultricies odio. Duis maximus elit id arcu aliquam, sit amet pulvinar mauris sodales. Donec sed felis in lacus faucibus ultrices. Nulla ut accumsan dui. Cras vel viverra purus. Praesent quis malesuada neque. Vivamus et mi ac augue egestas maximus facilisis ac massa.Etiam at diam nec dui volutpat efficitur. Cras faucibus urna non euismod vehicula. Suspendisse vel laoreet ligula. Duis eget nisi eget augue laoreet ultricies quis efficitur enim. Aliquam erat volutpat. Maecenas a risus turpis. Etiam non blandit velit, sed luctus tortor. Praesent at felis quam. Pellentesque nec libero tincidunt, maximus massa ut, imperdiet elit. Phasellus sit amet convallis risus. Sed nec sem erat. Suspendisse dapibus nunc sapien, sit amet placerat sem feugiat a. Phasellus lectus ante, lobortis eget magna a, luctus sodales elit. Aenean et iaculis magna. Vestibulum vel laoreet metus, sed dictum justo. Morbi ac interdum mi, ut ornare tortor. Curabitur faucibus, purus vitae mollis fringilla, turpis ligula venenatis elit, non maximus est nulla luctus mauris. In vel fringilla ex. Suspendisse potenti. Aliquam non porttitor dui. Pellentesque eu libero quis arcu fermentum vehicula ut id metus. Pellentesque elementum accumsan nisi eget pellentesque. Nulla dignissim condimentum elit, in vehicula purus efficitur in. Vivamus sit amet auctor metus. Pellentesque nec pretium diam. Phasellus viverra eu turpis a tincidunt. Cras vel justo nec felis efficitur placerat. Mauris at ipsum vel lorem ultrices sodales quis nec nisi. Quisque at venenatis sapien. Nulla facilisi.Vestibulum vestibulum libero sit amet dui dignissim ullamcorper. Donec venenatis luctus lorem vel congue. Nulla at purus maximus, pharetra nibh eu, vestibulum enim. Duis ultrices justo ut diam viverra, vel scelerisque augue convallis. Quisque id risus sed metus posuere semper a in leo. Nam eu quam purus. Nam eu tellus cursus, suscipit tellus id, condimentum turpis. Aenean vitae lectus mattis, vestibulum ligula id, maximus metus. Integer commodo sapien et feugiat tincidunt. Vivamus tellus purus, placerat sed eros vel, sagittis tempor orci. Nunc suscipit nec sem sit amet dapibus. Nunc nulla metus, vulputate vel tellus sit amet, interdum efficitur orci. Pellentesque vulputate sodales massa non tempus. Suspendisse potenti. Sed eleifend justo et orci auctor, in tempor leo viverra.",
        lessonVideoSrc: "dsafasdfasdf"
    },
    {
        lessonTitle: 'Understanding React Native',
        lessonNumber: "4",
        lessonDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi malesuada rutrum nisi pellentesque placerat. Phasellus gravida quam vitae ante pellentesque, id accumsan nulla blandit. Morbi malesuada aliquam massa vestibulum aliquet. Maecenas at ante sit amet eros fermentum elementum in id arcu. Vivamus laoreet ipsum lorem, nec rutrum erat pretium in. Quisque lacinia, lectus vel convallis ultricies, magna turpis tincidunt tortor, id pulvinar enim neque posuere ante. Aliquam cursus magna quis bibendum malesuada. Vestibulum euismod lacus sed elit euismod blandit. Pellentesque ac ultricies odio. Duis maximus elit id arcu aliquam, sit amet pulvinar mauris sodales. Donec sed felis in lacus faucibus ultrices. Nulla ut accumsan dui. Cras vel viverra purus. Praesent quis malesuada neque. Vivamus et mi ac augue egestas maximus facilisis ac massa.Etiam at diam nec dui volutpat efficitur. Cras faucibus urna non euismod vehicula. Suspendisse vel laoreet ligula. Duis eget nisi eget augue laoreet ultricies quis efficitur enim. Aliquam erat volutpat. Maecenas a risus turpis. Etiam non blandit velit, sed luctus tortor. Praesent at felis quam. Pellentesque nec libero tincidunt, maximus massa ut, imperdiet elit. Phasellus sit amet convallis risus. Sed nec sem erat. Suspendisse dapibus nunc sapien, sit amet placerat sem feugiat a. Phasellus lectus ante, lobortis eget magna a, luctus sodales elit. Aenean et iaculis magna. Vestibulum vel laoreet metus, sed dictum justo. Morbi ac interdum mi, ut ornare tortor. Curabitur faucibus, purus vitae mollis fringilla, turpis ligula venenatis elit, non maximus est nulla luctus mauris. In vel fringilla ex. Suspendisse potenti. Aliquam non porttitor dui. Pellentesque eu libero quis arcu fermentum vehicula ut id metus. Pellentesque elementum accumsan nisi eget pellentesque. Nulla dignissim condimentum elit, in vehicula purus efficitur in. Vivamus sit amet auctor metus. Pellentesque nec pretium diam. Phasellus viverra eu turpis a tincidunt. Cras vel justo nec felis efficitur placerat. Mauris at ipsum vel lorem ultrices sodales quis nec nisi. Quisque at venenatis sapien. Nulla facilisi.Vestibulum vestibulum libero sit amet dui dignissim ullamcorper. Donec venenatis luctus lorem vel congue. Nulla at purus maximus, pharetra nibh eu, vestibulum enim. Duis ultrices justo ut diam viverra, vel scelerisque augue convallis. Quisque id risus sed metus posuere semper a in leo. Nam eu quam purus. Nam eu tellus cursus, suscipit tellus id, condimentum turpis. Aenean vitae lectus mattis, vestibulum ligula id, maximus metus. Integer commodo sapien et feugiat tincidunt. Vivamus tellus purus, placerat sed eros vel, sagittis tempor orci. Nunc suscipit nec sem sit amet dapibus. Nunc nulla metus, vulputate vel tellus sit amet, interdum efficitur orci. Pellentesque vulputate sodales massa non tempus. Suspendisse potenti. Sed eleifend justo et orci auctor, in tempor leo viverra.",
        lessonVideoSrc: "dsafasdfasdf"
    },
    {
        lessonTitle: 'Understanding React Native',
        lessonNumber: "1",
        lessonDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi malesuada rutrum nisi pellentesque placerat. Phasellus gravida quam vitae ante pellentesque, id accumsan nulla blandit. Morbi malesuada aliquam massa vestibulum aliquet. Maecenas at ante sit amet eros fermentum elementum in id arcu. Vivamus laoreet ipsum lorem, nec rutrum erat pretium in. Quisque lacinia, lectus vel convallis ultricies, magna turpis tincidunt tortor, id pulvinar enim neque posuere ante. Aliquam cursus magna quis bibendum malesuada. Vestibulum euismod lacus sed elit euismod blandit. Pellentesque ac ultricies odio. Duis maximus elit id arcu aliquam, sit amet pulvinar mauris sodales. Donec sed felis in lacus faucibus ultrices. Nulla ut accumsan dui. Cras vel viverra purus. Praesent quis malesuada neque. Vivamus et mi ac augue egestas maximus facilisis ac massa.Etiam at diam nec dui volutpat efficitur. Cras faucibus urna non euismod vehicula. Suspendisse vel laoreet ligula. Duis eget nisi eget augue laoreet ultricies quis efficitur enim. Aliquam erat volutpat. Maecenas a risus turpis. Etiam non blandit velit, sed luctus tortor. Praesent at felis quam. Pellentesque nec libero tincidunt, maximus massa ut, imperdiet elit. Phasellus sit amet convallis risus. Sed nec sem erat. Suspendisse dapibus nunc sapien, sit amet placerat sem feugiat a. Phasellus lectus ante, lobortis eget magna a, luctus sodales elit. Aenean et iaculis magna. Vestibulum vel laoreet metus, sed dictum justo. Morbi ac interdum mi, ut ornare tortor. Curabitur faucibus, purus vitae mollis fringilla, turpis ligula venenatis elit, non maximus est nulla luctus mauris. In vel fringilla ex. Suspendisse potenti. Aliquam non porttitor dui. Pellentesque eu libero quis arcu fermentum vehicula ut id metus. Pellentesque elementum accumsan nisi eget pellentesque. Nulla dignissim condimentum elit, in vehicula purus efficitur in. Vivamus sit amet auctor metus. Pellentesque nec pretium diam. Phasellus viverra eu turpis a tincidunt. Cras vel justo nec felis efficitur placerat. Mauris at ipsum vel lorem ultrices sodales quis nec nisi. Quisque at venenatis sapien. Nulla facilisi.Vestibulum vestibulum libero sit amet dui dignissim ullamcorper. Donec venenatis luctus lorem vel congue. Nulla at purus maximus, pharetra nibh eu, vestibulum enim. Duis ultrices justo ut diam viverra, vel scelerisque augue convallis. Quisque id risus sed metus posuere semper a in leo. Nam eu quam purus. Nam eu tellus cursus, suscipit tellus id, condimentum turpis. Aenean vitae lectus mattis, vestibulum ligula id, maximus metus. Integer commodo sapien et feugiat tincidunt. Vivamus tellus purus, placerat sed eros vel, sagittis tempor orci. Nunc suscipit nec sem sit amet dapibus. Nunc nulla metus, vulputate vel tellus sit amet, interdum efficitur orci. Pellentesque vulputate sodales massa non tempus. Suspendisse potenti. Sed eleifend justo et orci auctor, in tempor leo viverra.",
        lessonVideoSrc: "dsafasdfasdf"
    },
    {
        lessonTitle: 'Understanding React Native',
        lessonNumber: "1",
        lessonDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi malesuada rutrum nisi pellentesque placerat. Phasellus gravida quam vitae ante pellentesque, id accumsan nulla blandit. Morbi malesuada aliquam massa vestibulum aliquet. Maecenas at ante sit amet eros fermentum elementum in id arcu. Vivamus laoreet ipsum lorem, nec rutrum erat pretium in. Quisque lacinia, lectus vel convallis ultricies, magna turpis tincidunt tortor, id pulvinar enim neque posuere ante. Aliquam cursus magna quis bibendum malesuada. Vestibulum euismod lacus sed elit euismod blandit. Pellentesque ac ultricies odio. Duis maximus elit id arcu aliquam, sit amet pulvinar mauris sodales. Donec sed felis in lacus faucibus ultrices. Nulla ut accumsan dui. Cras vel viverra purus. Praesent quis malesuada neque. Vivamus et mi ac augue egestas maximus facilisis ac massa.Etiam at diam nec dui volutpat efficitur. Cras faucibus urna non euismod vehicula. Suspendisse vel laoreet ligula. Duis eget nisi eget augue laoreet ultricies quis efficitur enim. Aliquam erat volutpat. Maecenas a risus turpis. Etiam non blandit velit, sed luctus tortor. Praesent at felis quam. Pellentesque nec libero tincidunt, maximus massa ut, imperdiet elit. Phasellus sit amet convallis risus. Sed nec sem erat. Suspendisse dapibus nunc sapien, sit amet placerat sem feugiat a. Phasellus lectus ante, lobortis eget magna a, luctus sodales elit. Aenean et iaculis magna. Vestibulum vel laoreet metus, sed dictum justo. Morbi ac interdum mi, ut ornare tortor. Curabitur faucibus, purus vitae mollis fringilla, turpis ligula venenatis elit, non maximus est nulla luctus mauris. In vel fringilla ex. Suspendisse potenti. Aliquam non porttitor dui. Pellentesque eu libero quis arcu fermentum vehicula ut id metus. Pellentesque elementum accumsan nisi eget pellentesque. Nulla dignissim condimentum elit, in vehicula purus efficitur in. Vivamus sit amet auctor metus. Pellentesque nec pretium diam. Phasellus viverra eu turpis a tincidunt. Cras vel justo nec felis efficitur placerat. Mauris at ipsum vel lorem ultrices sodales quis nec nisi. Quisque at venenatis sapien. Nulla facilisi.Vestibulum vestibulum libero sit amet dui dignissim ullamcorper. Donec venenatis luctus lorem vel congue. Nulla at purus maximus, pharetra nibh eu, vestibulum enim. Duis ultrices justo ut diam viverra, vel scelerisque augue convallis. Quisque id risus sed metus posuere semper a in leo. Nam eu quam purus. Nam eu tellus cursus, suscipit tellus id, condimentum turpis. Aenean vitae lectus mattis, vestibulum ligula id, maximus metus. Integer commodo sapien et feugiat tincidunt. Vivamus tellus purus, placerat sed eros vel, sagittis tempor orci. Nunc suscipit nec sem sit amet dapibus. Nunc nulla metus, vulputate vel tellus sit amet, interdum efficitur orci. Pellentesque vulputate sodales massa non tempus. Suspendisse potenti. Sed eleifend justo et orci auctor, in tempor leo viverra.",
        lessonVideoSrc: "dsafasdfasdf"
    },
    {
        lessonTitle: 'Understanding React Native',
        lessonNumber: "1",
        lessonDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi malesuada rutrum nisi pellentesque placerat. Phasellus gravida quam vitae ante pellentesque, id accumsan nulla blandit. Morbi malesuada aliquam massa vestibulum aliquet. Maecenas at ante sit amet eros fermentum elementum in id arcu. Vivamus laoreet ipsum lorem, nec rutrum erat pretium in. Quisque lacinia, lectus vel convallis ultricies, magna turpis tincidunt tortor, id pulvinar enim neque posuere ante. Aliquam cursus magna quis bibendum malesuada. Vestibulum euismod lacus sed elit euismod blandit. Pellentesque ac ultricies odio. Duis maximus elit id arcu aliquam, sit amet pulvinar mauris sodales. Donec sed felis in lacus faucibus ultrices. Nulla ut accumsan dui. Cras vel viverra purus. Praesent quis malesuada neque. Vivamus et mi ac augue egestas maximus facilisis ac massa.Etiam at diam nec dui volutpat efficitur. Cras faucibus urna non euismod vehicula. Suspendisse vel laoreet ligula. Duis eget nisi eget augue laoreet ultricies quis efficitur enim. Aliquam erat volutpat. Maecenas a risus turpis. Etiam non blandit velit, sed luctus tortor. Praesent at felis quam. Pellentesque nec libero tincidunt, maximus massa ut, imperdiet elit. Phasellus sit amet convallis risus. Sed nec sem erat. Suspendisse dapibus nunc sapien, sit amet placerat sem feugiat a. Phasellus lectus ante, lobortis eget magna a, luctus sodales elit. Aenean et iaculis magna. Vestibulum vel laoreet metus, sed dictum justo. Morbi ac interdum mi, ut ornare tortor. Curabitur faucibus, purus vitae mollis fringilla, turpis ligula venenatis elit, non maximus est nulla luctus mauris. In vel fringilla ex. Suspendisse potenti. Aliquam non porttitor dui. Pellentesque eu libero quis arcu fermentum vehicula ut id metus. Pellentesque elementum accumsan nisi eget pellentesque. Nulla dignissim condimentum elit, in vehicula purus efficitur in. Vivamus sit amet auctor metus. Pellentesque nec pretium diam. Phasellus viverra eu turpis a tincidunt. Cras vel justo nec felis efficitur placerat. Mauris at ipsum vel lorem ultrices sodales quis nec nisi. Quisque at venenatis sapien. Nulla facilisi.Vestibulum vestibulum libero sit amet dui dignissim ullamcorper. Donec venenatis luctus lorem vel congue. Nulla at purus maximus, pharetra nibh eu, vestibulum enim. Duis ultrices justo ut diam viverra, vel scelerisque augue convallis. Quisque id risus sed metus posuere semper a in leo. Nam eu quam purus. Nam eu tellus cursus, suscipit tellus id, condimentum turpis. Aenean vitae lectus mattis, vestibulum ligula id, maximus metus. Integer commodo sapien et feugiat tincidunt. Vivamus tellus purus, placerat sed eros vel, sagittis tempor orci. Nunc suscipit nec sem sit amet dapibus. Nunc nulla metus, vulputate vel tellus sit amet, interdum efficitur orci. Pellentesque vulputate sodales massa non tempus. Suspendisse potenti. Sed eleifend justo et orci auctor, in tempor leo viverra.",
        lessonVideoSrc: "dsafasdfasdf"
    }
]